Authentication:

  Environment:
    Scihub environment variable: COPERNICUS_AUTH
    EUMETSAT environment variable: EUMETSAT_AUTH
    # export AUTH="<user>:<password>"

  Copernicus Open Access Hub:
    User: <your-scihub-username>
    Password: <your-scihub-password>

  Copernicus Open Data Access:
    User: <your-eumetsat-username>
    Password: <your-eumetsat-password>

  File:
    Copernicus file: <file-with-scihub-authentication>
    EUMETSAT file: <file-with-eumetsat-authentication>
    # <user>:<password>

Search:

  Start date: 2021-10-01
  End date: today

  ROI:
    Geopackage:
      Layer: ROI
    WKT: <wkt>
    File: <file-with-wkt>

  Sentinel-1:
    Product type: GRD  # [SLC | GRD | OCN | RAW]
    Sensor mode: IW    # [IW | EW | WV | SM]

  Sentinel-2:
    Product type: S2MSI2A  # [S2MSI1C | S2MSI2A | S2MSI2Ap]
    Max cloud cover %: 10
    Tiles: [ T35VPG, T36VUM ]  # if specified, the ROI is ignored

  Sentinel-3:
    Instruments: [ OLCI, SLSTR ]
    Product level: L2
